import { Product } from './types';

/** Stub-katalog v1 — priser inkl. mva. Pant 0 på småsekker, 300 på storsekk. */
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Bjørkeved 40 L',
    type: 'Bjørk',
    price: 89,
    description: 'Tørr bjørk fra Lågendalen. Klar til peisen — hent selv eller få levert.',
    imageUrl: 'https://images.unsplash.com/photo-1520110120835-c96a9ef9569d',
    volumeLiters: 40,
    lengthCm: 30,
    unitLabel: 'sekk',
    pant: 0,
  },
  {
    id: '2',
    name: 'Bjørkeved 60 L',
    type: 'Bjørk',
    price: 129,
    description: 'Litt mer tørr bjørk i sekken. Lokal ved, klar når du fyrer.',
    imageUrl: 'https://images.unsplash.com/photo-1520110120835-c96a9ef9569d',
    volumeLiters: 60,
    lengthCm: 33,
    unitLabel: 'sekk',
    pant: 0,
  },
  {
    id: '3',
    name: 'Blandingsved 40 L',
    type: 'Miks',
    price: 69,
    description: 'Praktisk miks til hverdagsfyring. Tørr ved fra dalen.',
    imageUrl: 'https://images.unsplash.com/photo-1590054320984-7eb356230f25',
    volumeLiters: 40,
    lengthCm: 30,
    unitLabel: 'sekk',
    pant: 0,
  },
  {
    id: '4',
    name: 'Bjørkeved storsekk 1000 L',
    type: 'Bjørk',
    price: 1890,
    description: 'Stor sekk med tørr bjørk. Levert hjem eller hent selv.',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e',
    volumeLiters: 1000,
    lengthCm: 33,
    unitLabel: 'storsekk',
    pant: 300,
  },
  {
    id: '5',
    name: 'Blandingsved storsekk 1500 L',
    type: 'Miks',
    price: 2190,
    description: 'Stor blandingssekk — tørr og klar. Lokal ved med hjemlevering.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e',
    volumeLiters: 1500,
    lengthCm: 40,
    unitLabel: 'storsekk',
    pant: 300,
  },
  {
    id: '6',
    name: 'Furu 60 L',
    type: 'Furu',
    price: 99,
    description: 'Tørr furuved til peis og oppstart. Fra Lågendalen.',
    imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86',
    volumeLiters: 60,
    lengthCm: 30,
    unitLabel: 'sekk',
    pant: 0,
  },
];
